# https://github.com/googleapis/repo-automation-bots/tree/main/packages/release-please

handleGHRelease: true
manifest: true
manifestConfig: rp/release-please-config.json
manifestFile: rp/.release-please-manifest.json
