name: Detect Changed Apps
description: Searchs the project directories to determine which apps were changed

outputs:
    changes:
        description: An array of all changes with app names
        value: ${{ steps.changes.outputs.changes }}

runs:
    using: composite
    steps:
        - uses: dorny/paths-filter@v2
          id: changes
          with:
              base: ${{ github.ref }}
              filters: |
                  actions:
                    - '.github/actions/**'
                  workflows:
                    - '.github/workflows/**'
                  src:
                    - 'src/**'
