name: Code Style
on:
  pull_request:
    branches: [main]
    paths: ['**.js', '**.ts']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rome
        uses: rome/setup-rome@v0.4
        with:
          version: latest

      - name: Lint Code
        run: rome check .

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rome
        uses: rome/setup-rome@v0.4
        with:
          version: latest

      - name: Format Code
        run: rome format .
