name: Code Style
on:
  pull_request:
    branches: [main]
    paths: ['**.js', '**.ts']

jobs:
  rome-ci:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rome
        uses: elijaholmos/setup-rome@fix-version-input
        with:
          version: 10.0.1

      - name: Check Rome Version
        run: rome version

      - name: Run Linter & Formatter
        run: rome ci .
