name: Code Scan
on:
    push:
        branches: [main]
    pull_request:
    workflow_dispatch:

jobs:
    gitleaks:
        name: gitleaks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - run: wget -O .gitleaks.toml https://raw.githubusercontent.com/elijaholmos/.github/main/workflows/config/.gitleaks.toml
            - uses: gitleaks/gitleaks-action@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITLEAKS_NOTIFY_USER_LIST: '@elijaholmos'
