name: Prisma Validate
on:
  pull_request:
    branches: [main]
    # paths: ['**.js', '**.ts']

jobs:
  lint:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create .env file
        run: cat "DATABASE_URL=postgresql://postgres:password@localhost:5432" > .env

      - name: Run validator
        uses: elijaholmos/prisma-schema-validate@dev
