name: Pull Request Label

on:
  pull_request:

jobs:
  label-size:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1.8.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size: xs'
          xs_max_size: 1
          s_label: 'size: s'
          s_max_size: 2
          m_label: 'size: m'
          m_max_size: 3
          l_label: 'size: l'
          l_max_size: 4
          xl_label: 'size: xl'
          fail_if_xl: false
          message_if_xl: ''
          files_to_ignore: |
            "pnpm-lock.yaml"
            ".terraform.lock.hcl"
