name: Pull Request Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  inherit-parent-action:
    uses: elijaholmos/.github/workflows/pull-request-title.yml@main
