on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions: write-all

name: release-please

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - uses: google-github-actions/release-please-action@v3
              with:
                  command: manifest
                  config-file: .github/workflows/release-please-config.json
                  manifest-file: .github/workflows/.release-please-manifest.json
